apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-items-test
  labels:
    app: graphql-items
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-items
  template:
    metadata:
      labels:
        app: graphql-items
    spec:
      containers:
        - name: graphql-items
          image: <docker-username>/graphql-items:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: testing
